version: '3.8'
services:
  web:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /etc/msmtprc:/etc/msmtprc:ro  # Mount external msmtp config as read-only
    environment:
      - NODE_ENV=production
    command: ["node", "app.js"]
